# Файл docker-compose.yml

# Версия docker-compose
version: '3'

# Перечень volume
volumes:
  pg_data:
  # Новый volume — для статических файлов
  static:

# Перечень контейнеров
services:
  # Имя и описание первого контейнера; имя выбирает разработчик. 
  # Это контейнер БД
  db:
    # Из какого образа запустить контейнер:
    image: postgres:13.10
    # Файл (или список файлов) с переменными окружения
    env_file: .env
    # Какой volume подключить для этого контейнера
    volumes:
      - pg_data:/var/lib/postgresql/data
  # Имя и описание контейнера с бэкендом
  backend:
    # Из какого Dockerfile собирать образ для этого контейнера:
    build: ./backend/
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
    # Какие контейнеры нужно запустить до старта этого контейнера:
    depends_on:
      - db
  # Имя третьего контейнера. Это контейнер с фронтендом
  frontend:
    env_file: .env
    build: ./frontend/
    # Спринт 17/18 → Тема 2/5: Docker: приложение в коробке → Урок 10/11:
    # объявить связь директории /frontend_static/ c volume static (при этом директория будет создана автоматически);
    # добавить ключ command и выполнить команду копирования файлов: cp -r /app/build/. /frontend_static/.
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
# Добавляем новый контейнер: gateway.
  gateway:
    # Сбилдить и запустить образ, 
    # описанный в Dockerfile в папке gateway
    build: ./gateway/
    # Зачем это env_file: .env не знаю в конце урока появилось без объяснения
    # Спринт 17/18 → Тема 2/5: Docker: приложение в коробке → Урок 10/11
    env_file: .env
    # Ключ ports устанавливает
    # перенаправление всех запросов с порта 8000 хоста
    # на порт 80 контейнера.
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 8000:80 